bro_app/urls.py
from django.urls import path

from bro_app import views

from bro_app.views import OrderReg, Orderlist ,Orderdetail , OrderUpdate, OrderDelete 

app_name='bro_app'

urlpatterns = [
    path('home', views.home, name = "home"),
    path('product', views.product, name = "product"),
    path('service', views.service, name = "service"),
    path('contact', views.contact, name = "contact"),
    path('aboutus', views.aboutus, name = "aboutus"),
    

   path('Orderreg', OrderReg.as_view(), name = 'Orderreg'),
   path('<pk>/Orderdetail', Orderdetail.as_view(), name = 'Orderdetail'),
   path('',Orderlist.as_view(), name = 'Orderlist'),
   path('<pk>/Orderupdate',OrderUpdate.as_view(),name = 'Orderupdate'),
   path('<pk>/Orderdelete', OrderDelete.as_view(), name = 'Orderdelete'),


### for get ad post
    path('dhana',views.dhana, name = 'dhana'),
    path('get1', views.get1, name = 'get1'),
    path('post1', views.post1, name = 'post1'),

###  for Fnuction based view.
    path('form', views.form,name  = 'form'), ##Order registration
    path('Orders', views.Order, name = "Orders"), #Orderlist
    path('detail/<int:id>', views.detail, name = 'detail'), # Order Detail
    path('update/<int:id>', views.update, name = 'update'), # Stuudent update
    path('delete/<int:id>', views.delete, name = 'delete'), #Order Update

### for user registratio, sign-in sign-out
    path('index', views.index, name = 'index'),
    path('register', views.register, name = 'register'),
    path('login_reg', views.login_reg, name = 'login_reg'),
    path('logout', views.logoutuser, name = 'logout'),

    
    path('', views.home, name='home'),
    path("image",views.image, name='image'),
    path('images', views.images, name='images'),
    
    path('product', views.product, name='product'),
    path('products', views.products, name='products'),
    path('order/<int:id>', views.order, name='order'),
    path('kart', views.kart  , name='kart '),
   
    
]



projectX/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bro_app.urls')),
]

templates/FBV/delete.html
{% include 'base.html' %}

{% block content %}

<div class="main">
<form method="POST">
    {% csrf_token %}

<h4>    Are you want to delete this item ?</h4><br>
    <div>
        <table style="width:100%"; border-spacing: 5px;>

            <tr>
                
                <th >Name</th>
                <th >quantity</th>
                <th >price</th>
                <th >availability</th>
                
            </tr>
                            
             <tr>
                
                <td>{{ data.name }}</td>
                <td>{{ data.quantity }}</td>
                <td>{{ data.price }}</td>      
                <td>{{ data.availability }}</td>          

            </tr>

   
        </table> <br><br>
            <input type="submit" value="Yes, Delete" />
            <a href="/">Cancel </a>
            
    </div>
</form>
</div>


<a href="{% url 'bro_app:Orders'%}" class="btn btn-primary" style="border-radius: 20px; margin-left: 30px;">
    Order List    
</a>


{% endblock %}

templates/FBV/detail.html
{% include 'base.html' %}

{% block content %}
Name         :{{ object.name}}<br>
quantity     :{{ object.quantity}} <br>
price        : {{object.price}}<br>
availability : {{object.availability}}<br>

<a href="{% url 'bro_app:Orders'%}" class="btn btn-primary" style="border-radius: 20px; margin-left: 30px;">
   Order List    
</a>


{% endblock %}

templates/FBV/form.html
{% extends 'base.html' %}

{% block content %}

<h1>
    Today we are going to discuss on FBV - Function based views.
</h1>
<div>
    <table style="width:100%"; border-spacing: 5px;>

             <tr>
               
               <th>Name</th>
               <th >quantity</th>
               <th >price</th>
               <th >availability</th>
               <th>Detail</th>
               <th>Update</th>
               <th>Delete</th>               
             </tr>
                     {% for a in Ord %}
           <tr>
              
               <td>{{ a.name }}</td>
               <td>{{ a.quantity }}</td>
               <td>{{ a.price }}</td>     
               <td>{{ a.availability}}</td>          
               <td><a href = "detail/{{ a.id }}"  button class = "btn btn-success">Details</button></a></td>
               <td><a href = "update/{{ a.id }}"  button class="btn btn-primary">Update</button></a></td>				              
               <td><a href = "delete/{{ a.id }}"  button class="btn btn-danger">Delete</button></a></td>

           </tr>
       {% endfor %}
   </table> 
<hr><hr>
<br><br>


For registration please fill in the form.

<div>
    <form action = "" method = "post">
        {% csrf_token %}
        {{form.as_p }}
        <input type="submit" value= "Submit">
    </form>
</div>


{% endblock %}

templates/FBV/update.html
{% include 'base.html' %}

{% block content %}


<div class="main">
    <form method="POST">
        {% csrf_token %}

    <h4>    Do you want to Update this item ? </h4><br>
<div>
     <table style="width:100%"; border-spacing: 5px;>

              <tr>
                
                <th >Name</th>
                <th >quantity</th>
                <th >price</th>
                <th >availability</th>
                
              </tr>
                    
            <tr>
                
                <td>{{ data.name }}</td>
                <td>{{ data.quantity }}</td>
                <td>{{ data.price }}</td>
                <td>{{ data.availability }}</td>
                

            </tr>
     

    </table> <br><br>
    <div>
		<h1>Enter the values to be updated here.</h1>
    			{{ form.as_p }}
    </div>

        <input type="submit" value="Yes, Update" />
        <a href="/">Cancel </a>
    </form>
</div>


<a href="{% url 'bro_app:Orders'%}" class="btn btn-primary" style="border-radius: 20px; margin-left: 30px;">
   Order List    
</a>


{% endblock %}